### ISSUE TITLE
Show all tours modal - a11y

### ISSUE THREAD

**Issue by brianteeman** [joomla-projects/gsoc22_guided-tour#117]
### Steps to reproduce the issue
using the tab key on your keyboard navigate to the tours dropdown
press enter key to open dropdown
use tab or down arrow key to navigate to "Show all"
press enter to open modal

### Expected result
navigate between the links with the keyboard

### Actual result
the focus is only ever between the X and Close 

### Additional comments

This is because they are neither links or buttons but li list elements

**Comment by obuisard** [comment]
Thank you, on it :-)

**Comment by brianteeman** [comment]
let me know if you get stuck. I try not to be at the computer now until saturday evening

**Comment by obuisard** [comment]
I will. All good, thanks!

**Comment by obuisard** [comment]
Got it to work
