### ISSUE TITLE
"Take a Tour" button visible before logging in

### ISSUE THREAD

**Issue by crystalenka** [joomla-projects/gsoc22_guided-tour#27]
<img width="732" alt="Screenshot 2023-02-07 at 10 39 08" src="https://user-images.githubusercontent.com/9141288/217194280-17c954a4-ac7d-4163-bc96-20aee5ee574c.png">

Also, if you attempt to take the tour, it takes you through the steps but does not show the screen.

I'm thinking this could present issues on sites where different user groups have specific permissions. Either the tour should check permissions of the component it's tied to, or an error should display if the tour cannot be completed because of permissions issues.

**Comment by khu5h1** [comment]
Thank you @crystalenka for reporting the issue. I am working on it and will raise the PR for the same.

**Comment by brianteeman** [comment]
Its not just the button that is present. The tours run as well

![image](https://user-images.githubusercontent.com/1296369/217854974-e4d85c7c-9884-48e7-81f1-e689e8c9b4ae.png)

**Comment by obuisard** [comment]
Thank you for reporting this! Fixed with PR #55
