### ISSUE TITLE
UX - required interaction unclear

### ISSUE THREAD

**Issue by crystalenka** [joomla-projects/gsoc22_guided-tour#28]
When interaction is required to move forward, it's not clear to the user.

My initial reaction in the screenshotted step was to click "back", even though I meant to move forward.
<img width="443" alt="Screenshot 2023-02-07 at 10 49 08" src="https://user-images.githubusercontent.com/9141288/217197167-1c080295-8f65-464e-adc5-cb61b73aa474.png">

Suggestion would be to always align "back" button to the beginning of the line, and in the case that interaction is required, make it clear. Maybe something like so:
<img width="443" alt="Screenshot 2023-02-07 at 10 54 09" src="https://user-images.githubusercontent.com/9141288/217197687-49c25d25-28b3-4a97-a885-20a9f904a4fe.png">

**Comment by obuisard** [comment]
As we are using a third-party library, the content of the popup is pretty inflexible. 
I do agree about the back button (and we can possibly do something about it), but the text in parenthesis, I am not so sure. However, we can change the wording of the title and/or the description to include the additional help (HTML tags are allowed).

**Comment by khu5h1** [comment]
@crystalenka Thanks for your feedback. I also agree with the same.

As the content of the popup is not too flexible, instead can we update the title/description by mentioning `Click on the +New Button highlighted by the pop-up to create a new tour`, for better understanding.

**Comment by brianteeman** [comment]
its only css to change the position so that shepherd-button-secondary is always on the left and shepherd-button-primary is always on the right

**Comment by brianteeman** [comment]
Should have said "start" and "end" instead of lft/right as this would change in an RTL language

**Comment by obuisard** [comment]
`.shepherd-footer` needs to have `justify-content` set to `space-between`

**Comment by brianteeman** [comment]
> `.shepherd-footer` needs to have `justify-content` set to `space-between`

in addition to start and end - otherwise it doesnt work when there is only one button

**Comment by obuisard** [comment]
The footer being a flex element, the placement of elements was dictated by flex, rendering proper placement impossible. The footer has been replaced with grid, which is more flexible.
