### ISSUE TITLE
ACL

### ISSUE THREAD

**Issue by brianteeman** [joomla-projects/gsoc22_guided-tour#33]
On a clean install the permissions for every guided tour is the same. ie anyone with admin access sees all the tours.

This is a problem as not all users have access to all components and they just get ther unfriendly 403 error
![image](https://user-images.githubusercontent.com/1296369/217859244-0dda28cf-fd4a-46ac-a777-8db0b1384ef5.png)

What should be changed is that the list of tours displayed in the dropdown should check to see if the user has access to the component and if not then the tour should be removed from the list

**Comment by obuisard** [comment]
Thank you for reporting this! Fixed with PR #55.
