### ISSUE TITLE
ACL again

### ISSUE THREAD

**Issue by brianteeman** [joomla-projects/gsoc22_guided-tour#34]
### Steps to reproduce the issue
Log in as a manager
Try to take the very first tour - how to create a guide tour or the how to create a user
You get the ugly 403 as reported in #33 
Now click on the tour a second time and now it starts even though you dont see the actual component

![touracl2](https://user-images.githubusercontent.com/1296369/217862778-caa91f13-eff4-405f-9481-906235ac9ad3.gif)

**Comment by obuisard** [comment]
Thank you! Fixed with PR #55.
