### ISSUE TITLE
Missing string

### ISSUE THREAD

**Issue by brianteeman** [joomla-projects/gsoc22_guided-tour#37]
COM_GUIDEDTOURS_TOUR_ARTICLES_STEP_SAVECLOSE_TITLE

**Comment by obuisard** [comment]
I have encountered this one as well. But the key is present in the language file!

**Comment by brianteeman** [comment]
found it - there is an extra space in the sql

![image](https://user-images.githubusercontent.com/1296369/218168907-b69ea072-2414-4e0a-a879-b0e9086d959a.png)

**Comment by brianteeman** [comment]
not sure why that would make a difference though

**Comment by obuisard** [comment]
Good catch!

**Comment by obuisard** [comment]
Thanks Brian!
