### ISSUE TITLE
Tour Ordering

### ISSUE THREAD

**Issue by brianteeman** [joomla-projects/gsoc22_guided-tour#38]
### Steps to reproduce the issue
In the list o0f available guided tours try to change the order that they will be displayed in, in the usual way

### Expected result
The order in the dropdown changes 

### Actual result
Nothing happens at all. Presumably this is because although there is an ordering field in the database table there is no code to write a value into it

**Comment by obuisard** [comment]
Fixed in upcoming PR - Please don't try and fix this.

**Comment by brianteeman** [comment]
closed as fixed
