### ISSUE TITLE
Step Ordering

### ISSUE THREAD

**Issue by brianteeman** [joomla-projects/gsoc22_guided-tour#39]
Just like with tours you can drag and drop steps to change the order but there is no change in the database at all

Looking in the database you can see that there are two possible fields for this - ordering and step no. Not sure why there are two as their name suggest they would be for the same thing.

However just as with the tours - there is no code to change the values and every step has the same values

![image](https://user-images.githubusercontent.com/1296369/217881416-36ccc811-4fc5-4711-9e24-8f95173df894.png)

**Comment by brianteeman** [comment]
This obviously means that when creating a tour you can not change the order of the steps but also and more importantly you can not go back and add a missing step. 

Currently you have to create all the steps  in the correct order and the only option if you miss a step is to delete all the following steps, insert the new one and then recreate all the steps you had deleted.

**Comment by obuisard** [comment]
Still not working properly. Will take another look

**Comment by obuisard** [comment]
Fixed, there was a type in the code!

**Comment by brianteeman** [comment]
confirmed as fixed
