### ISSUE TITLE
guided tour/step description xtd-editor - images path

### ISSUE THREAD

**Issue by brianteeman** [joomla-projects/gsoc22_guided-tour#41]
The description of the tour is the first screen displayed when a user selects a tour so it would be nice to be able to use images

The description field does not restrict which of the xtd-editor plugins are available. This is obviously wrong as this description is only displayed in the admin and the links the xtd-editor plugins generate are all for site modules, site menu, or require content plugihns to run etc

Thats simple to fix in the field sml definition

But adding an image is something that you would definitely want to do. However if you add an image it will never be displayed as the path saved is relative not absolute

![image](https://user-images.githubusercontent.com/1296369/217885919-67cd9d81-5dcb-4abf-8910-8ef577370402.png)

![image](https://user-images.githubusercontent.com/1296369/217886260-1343bfde-2203-4cf2-837f-06416361a8ea.png)

**Comment by brianteeman** [comment]
The code here will fix the image https://github.com/joomla/joomla-cms/blob/4.2-dev/administrator/modules/mod_custom/mod_custom.php

**Comment by obuisard** [comment]
The description field needs hide="readmore,pagebreak,module,menu,fields,contact,article"

**Comment by brianteeman** [comment]
confirmed as fixed
