### ISSUE TITLE
Guided Tour - URL should be required

### ISSUE THREAD

**Issue by brianteeman** [joomla-projects/gsoc22_guided-tour#44]
### Steps to reproduce the issue
It is now clearer to me that when you create a tour that the url field should be a required field which it is not. If you were to leave it empty then when you click on the  tour the frontend of the site opens. I assumed that if there was no url entered the tour description would be displayed on whatever the current screen was

**Comment by brianteeman** [comment]
Confirmed as fixed but maybe it should be moved between the title and the description

**Comment by obuisard** [comment]
I agree that having a required field at the bottom of the page is not user friendly

**Comment by brianteeman** [comment]
The closest core example I can think of is com_newsfeeds 

![image](https://user-images.githubusercontent.com/1296369/218340660-4ed7b63b-6670-4f0c-99eb-011d894e678e.png)

**Comment by brianteeman** [comment]
confirmd as fixed
