### ISSUE TITLE
Missing language column

### ISSUE THREAD

**Issue by brianteeman** [joomla-projects/gsoc22_guided-tour#48]
All the list views check to see if it is a multilingual site and if it is display a language column 
![image](https://user-images.githubusercontent.com/1296369/217893264-daa5e16a-9c7a-474b-a98a-08fedf149cc8.png)

There is no way to tell what language has been selected for a tour from the list view as it does not have this column
![image](https://user-images.githubusercontent.com/1296369/217893409-a395b7dd-cc7c-4019-98be-f19a49017b57.png)

**Comment by obuisard** [comment]
Addressed in PR #84

**Comment by brianteeman** [comment]
confirmed as fixed
