### ISSUE TITLE
Steps - title

### ISSUE THREAD

**Issue by brianteeman** [joomla-projects/gsoc22_guided-tour#51]
### Steps to reproduce the issue
Hover on the title of a step

### Expected result
Something like this
![image](https://user-images.githubusercontent.com/1296369/217943153-021a6b0f-c504-4038-9f54-fd3c3f06330b.png)

### Actual result
![image](https://user-images.githubusercontent.com/1296369/217943166-21138387-4a38-4a83-917f-6809bfa1529d.png)

**Comment by obuisard** [comment]
This happens because the lists show the title/description without striping the html tags.

**Comment by brianteeman** [comment]
confirmed as fixed
