### ISSUE TITLE
Steps Column width

### ISSUE THREAD

**Issue by brianteeman** [joomla-projects/gsoc22_guided-tour#64]
### Steps to reproduce the issue
Create a new tour with two steps. Give each step a very short name

### Expected result
![image](https://user-images.githubusercontent.com/1296369/218300404-b0cefe17-dd7b-4153-ac69-e88d1a36a847.png)

### Actual result
![image](https://user-images.githubusercontent.com/1296369/218300431-e7545b0a-e0bf-4360-ba3e-f4abe380ccc8.png)

**Comment by aze088** [comment]
Think I fixed the issue but won't know until code is merged

**Comment by brianteeman** [comment]
not fixed

**Comment by brianteeman** [comment]
Closed see #94
