### ISSUE TITLE
Start Button

### ISSUE THREAD

**Issue by brianteeman** [joomla-projects/gsoc22_guided-tour#65]
I think this may be the result of a previous css change 

When you start a tour the "Start" button should be aligned end not aligned start. That way it is consistent with th Next button etc

![image](https://user-images.githubusercontent.com/1296369/218300506-fd845e85-9b59-4bec-bbe5-44a61a8e6f9c.png)

**Comment by obuisard** [comment]
This has been fixed, not merged #59

**Comment by brianteeman** [comment]
are you sure? I checked with #59

**Comment by obuisard** [comment]
Yes sorry, I have to check it out. It was working on my computer yesterday. Maybe a cache issue. I reopened this issue to make sure I don't forget to double check.

**Comment by obuisard** [comment]
Ok, Brian @brianteeman, I have double checked this one on 2 different systems and I do get the start button at the right place.
Can you verify on your end? Thank you!

**Comment by brianteeman** [comment]
my bad - looks like i hadnt rebuilt the css

**Comment by obuisard** [comment]
Thank you Brian!
