### ISSUE TITLE
Published or Enabled

### ISSUE THREAD

**Issue by brianteeman** [joomla-projects/gsoc22_guided-tour#70]
Not sure I really care if it is published/unpublished or enabled/disabled but it should be consistent.

Currently the messages use enabled/disabled and the links use published/unpublished.

![image](https://user-images.githubusercontent.com/1296369/218306719-2d150ea1-531b-4797-bda8-112cd6850ac6.png)

**Comment by khu5h1** [comment]
Corrected in `infra-guided-tour` branch.

**Comment by brianteeman** [comment]
Confirmed fixed
