### ISSUE TITLE
Steps messages

### ISSUE THREAD

**Issue by brianteeman** [joomla-projects/gsoc22_guided-tour#71]
### Steps to reproduce the issue
publish or unpublish a step

### Expected result
message refers to  steps

### Actual result
message refers to tours

![image](https://user-images.githubusercontent.com/1296369/218306813-b00e4685-7ebf-45c5-9ace-c2c325091754.png)

**Comment by obuisard** [comment]
Replaced 'tour' with 'item' because these messages are created automatically from the name of the extension and there is no way to distinguish tour from step.

**Comment by brianteeman** [comment]
Confirmed as fixed
