### ISSUE TITLE
Default Permissions

### ISSUE THREAD

**Issue by brianteeman** [joomla-projects/gsoc22_guided-tour#73]
Check the permissions tab for any tour and step.

The default permissions are not correct as they give permission to users who do not have admin access eg publishers

Example Step

![image](https://user-images.githubusercontent.com/1296369/218307428-b5c13172-1882-41e5-a8de-3a0f05db3833.png)

**Comment by obuisard** [comment]
Looks like is the same for other admin-only components. Not sure what to do here.

**Comment by brianteeman** [comment]
never noticed it. good spot. closing here will open an issue on the main repo
