### ISSUE TITLE
Edit Layout

### ISSUE THREAD

**Issue by brianteeman** [joomla-projects/gsoc22_guided-tour#75]
### Steps to reproduce the issue
Edit or create any tour or step

### Expected result
Same UI as the rest of Joomla

![image](https://user-images.githubusercontent.com/1296369/218307757-dbb00254-07ea-4205-b1a4-bc0bad63f56b.png)

### Actual result

![image](https://user-images.githubusercontent.com/1296369/218307793-4a9fa5f4-c789-4797-9674-e9a9a39757dd.png)

**Comment by brianteeman** [comment]
did you forget to commit the fix?

**Comment by obuisard** [comment]
It's not merged yet.

**Comment by brianteeman** [comment]
still not merged ??

**Comment by brianteeman** [comment]
Still not seeing this as being fixed
