### ISSUE TITLE
[Issue]: CSS issue with Tour Title

### ISSUE THREAD

**Issue by jatinS-dev** [joomla-projects/gsoc22_guided-tour#8]
### Steps to reproduce the issue

- Go to the Guided Tour Component list view.
- add the lengthy tour title 

### Expected result

- The Title should fit in the title area of the Tour

### Result

![1](https://user-images.githubusercontent.com/66058203/183820119-33b6b97b-d26c-4018-8805-8b15263ff784.png)

**Comment by avezqureshi14** [comment]
Hey can you assign this issue to me

**Comment by obuisard** [comment]
This is fixed in infra-guided-tour

**Comment by obuisard** [comment]
Thank you for reporting the issue!
