### ISSUE TITLE
Component Permissions

### ISSUE THREAD

**Issue by brianteeman** [joomla-projects/gsoc22_guided-tour#82]
Open the component options and make any change and then save

Just like in the tours and steps the changes are not _saved_

Looking at the assets table you will see why

![image](https://user-images.githubusercontent.com/1296369/218328003-3853ac72-d580-402a-9bc0-ce8381ba05b0.png)

The first line is the asset from the installation

The third line is the one created when you saved the component options.

Obviously the name of one of those is wrong

**Comment by obuisard** [comment]
There is wrong naming on the component.

**Comment by brianteeman** [comment]
Confirming that you can now save changes in the component
