### ISSUE TITLE
Orphaned Steps

### ISSUE THREAD

**Issue by brianteeman** [joomla-projects/gsoc22_guided-tour#85]
### Steps to reproduce the issue
Delete all tours and empty trash

### Expected result
the database table for both guided_tours and guided_steps are now empty

### Actual result
only guided_tours is empty

there is now no way to delete all the orphaned steps from the database

**Comment by obuisard** [comment]
Khushi is working on this

**Comment by obuisard** [comment]
Fixed

**Comment by brianteeman** [comment]
confirmed as fixed
