### ISSUE TITLE
access column in tours

### ISSUE THREAD

**Issue by brianteeman** [joomla-projects/gsoc22_guided-tour#89]
the code in #84 to add the access column is **completely wrong.** It is reinventing a wheel that is already perfectly round and replacing it with a triangle.

Hint 1: Whenever you have if,,elseif..elseif..elseif..else then you are doing it wrong
Hint 2: Check the other components - see how it is fone there and do the same here
Hint 3: view access levels are not static. New ones can be created by the site owner at any time

**Comment by obuisard** [comment]
I have re-assigned this task to Aaron. Totally my fault on this one.

**Comment by aze088** [comment]
fixed on my end, waiting to be merged.

**Comment by brianteeman** [comment]
Confirmed as fixed
